### ISSUE TITLE
LogBad

### ISSUE THREAD

**Issue by PiggleMcDiggle** [HorizonsEndMC/IonCore#39]
![Screenshot_20220228-121630_One UI Home](https://user-images.githubusercontent.com/56192681/155982215-417805d8-9b76-4be4-b4cb-34062564a779.jpg)
Ban Peter

**Comment by Peter-Crawley** [comment]
Stop talking through GitHub issues otherwise I will prevent you from opening issues.

**Comment by PiggleMcDiggle** [comment]
How else can I communicate?

**Comment by Peter-Crawley** [comment]
Idk IRC lol

**Comment by PiggleMcDiggle** [comment]
What do any of those acronyms even mean?

**Comment by Peter-Crawley** [comment]
:man_facepalming:

**Comment by PiggleMcDiggle** [comment]
?

**Comment by Peter-Crawley** [comment]
idk = I don't know
IRC = Internet Relay Chat (old form of chat room from like the 90s which some people still use)
