### ISSUE TITLE
Death without Cryo Causes weird respawning

### ISSUE THREAD

**Issue by Makavelian4200** [HorizonsEndMC/IonCore#84]
If you die on a planet without a cryopod, you get sent to a random spot in the planet instead of to the spawn station. This happened on the planet Aret to player, they spawned in the top left of the map instead of at spawn station.

**Comment by Peter-Crawley** [comment]
This is most likely a result of screwed up Multiverse configuration.

**Comment by Peter-Crawley** [comment]
Has this been resolved?

**Comment by trainb0y1** [comment]
Possibly related to #103
